# frontend/Dockerfile.dev
FROM node:18

WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY app/package.json app/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY app ./

EXPOSE 3000

CMD ["npm", "run", "dev"]