version: "3.7"

services:
    api:
        build: zontahnos
        environment:
          - PORT=8080
        ports:
          - 8080:8080 # API UI
        tty: true
        stdin_open: true

    influxdb2:
      image: influxdb:2
      ports:
        - 8086:8086 # InfluxDB UI
      environment:
        DOCKER_INFLUXDB_INIT_MODE: setup
        DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
        DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
        DOCKER_INFLUXDB_INIT_ORG: netsmart
        DOCKER_INFLUXDB_INIT_BUCKET: network_monitoring
      volumes:
          - influxdb2-data:/var/lib/influxdb2
          - influxdb2-config:/etc/influxdb2

    grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"  # Grafana UI
      environment:
        - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
        - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      volumes:
        - grafana_data:/var/lib/grafana
      depends_on:
        - influxdb2
      restart: unless-stopped

volumes:
  influxdb2-data:
  influxdb2-config:
  grafana_data:
