FROM python:3.10

WORKDIR /app

COPY requirements-tests.txt requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

WORKDIR /app/app

ENV PYTHONPATH=/app

# CMD ["tail", "-f", "/dev/null"]
CMD ["sh", "-c", "pytest ../tests"]