services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK  # Required to enable in-memory encryption
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_API_ADDR=${VAULT_API_ADDR}
      - VAULT_LOG_LEVEL=${VAULT_LOG_LEVEL}
      - VAULT_UI=${VAULT_UI}
    entrypoint: vault server -dev -dev-root-token-id=${VAULT_DEV_ROOT_TOKEN_ID} -dev-listen-address=0.0.0.0:8200
    volumes:
      - test-vault-data:/vault/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - test-postgres-data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - test-grafana-data:/var/lib/grafana
    depends_on:
      - influxdb2
      - vault
    restart: unless-stopped

  influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086 # InfluxDB UI
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_INIT_BUCKET}
    volumes:
      - test-influxdb2-data:/var/lib/influxdb2
      - test-influxdb2-config:/etc/influxdb2

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - PORT=8080
    volumes:
      - ./tests:/app/tests
      - ./zontahnos/app/app:/app/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  test-influxdb2-data:
  test-influxdb2-config:
  test-grafana-data:
  test-vault-data:
  test-postgres-data: