FROM python:3.10

WORKDIR /app

COPY requirements-dev.txt requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

WORKDIR /app/app
ENV PYTHONPATH=/app

CMD ["gunicorn", "main:app", "--reload", "--bind", "0.0.0.0:8080", "-k", "uvicorn.workers.UvicornWorker"]